test_execution_shutdown_failure.byte: failure: This error was triggered on purpose.
test_execution_shutdown_failure.byte: failure: This error was also triggered on purpose.
